# -*- coding: utf-8 -*-
"""helmet_cnn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QJfPe1o8tDX4d52NlVPvtoc-NuR4Jwmz
"""

!pip install ultralytics opencv-python tensorflow albumentations

!pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/anushkagovindkadam/smart-helmet-detection-using-dl/data")

import os

print(os.listdir("/content/smart-helmet-detection-using-dl/data"))
print(os.listdir("/content/smart-helmet-detection-using-dl/data/train"))
print(os.listdir("/content/smart-helmet-detection-using-dl/data/valid"))

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/smart-helmet-detection-using-dl/data/data.yaml",
    epochs=50,
    imgsz=640,
    batch=16
)

HELMET_CLASSES = [0, 3]
NO_HELMET_CLASSES = [5, 6]
PERSON_CLASSES = HELMET_CLASSES + NO_HELMET_CLASSES

import cv2
import os

def yolo_to_bbox(w, h, x, y, bw, bh):
    return (
        int((x - bw/2) * w),
        int((y - bh/2) * h),
        int((x + bw/2) * w),
        int((y + bh/2) * h)
    )

def create_cnn_dataset(img_dir, label_dir, out_dir):
    for img_name in os.listdir(img_dir):
        if not img_name.endswith(".jpg"):
            continue

        img_path = os.path.join(img_dir, img_name)
        label_path = os.path.join(label_dir, img_name.replace(".jpg", ".txt"))

        if not os.path.exists(label_path):
            continue

        img = cv2.imread(img_path)
        h, w, _ = img.shape

        with open(label_path) as f:
            for i, line in enumerate(f):
                cls, x, y, bw, bh = map(float, line.split())
                cls = int(cls)

                if cls not in PERSON_CLASSES:
                    continue  # skip bike

                x1, y1, x2, y2 = yolo_to_bbox(w, h, x, y, bw, bh)
                crop = img[y1:y2, x1:x2]

                if crop.size == 0:
                    continue

                label = "helmet" if cls in HELMET_CLASSES else "no_helmet"
                save_dir = os.path.join(out_dir, label)
                os.makedirs(save_dir, exist_ok=True)

                cv2.imwrite(f"{save_dir}/{img_name}_{i}.jpg", crop)

BASE_PATH = "/content/smart-helmet-detection-using-dl"

# YOLO dataset paths
TRAIN_IMG = f"{BASE_PATH}/data/train/images"
TRAIN_LBL = f"{BASE_PATH}/data/train/labels"

VAL_IMG = f"{BASE_PATH}/data/valid/images"
VAL_LBL = f"{BASE_PATH}/data/valid/labels"

# CNN dataset output paths
CNN_TRAIN = f"{BASE_PATH}/cnn_dataset/train"
CNN_VAL = f"{BASE_PATH}/cnn_dataset/val"

# Create datasets
create_cnn_dataset(TRAIN_IMG, TRAIN_LBL, CNN_TRAIN)
create_cnn_dataset(VAL_IMG, VAL_LBL, CNN_VAL)

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

IMG_SIZE = 128
BATCH = 32

train_gen = ImageDataGenerator(rescale=1./255)
val_gen = ImageDataGenerator(rescale=1./255)

train_data = train_gen.flow_from_directory(
    "/content/smart-helmet-detection-using-dl/cnn_dataset/train",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH,
    class_mode="binary"
)

val_data = val_gen.flow_from_directory(
    "/content/smart-helmet-detection-using-dl/cnn_dataset/val",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH,
    class_mode="binary"
)

!ls /content/smart-helmet-detection-using-dl/cnn_dataset/train

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout

model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()

model.fit(
    train_data,
    validation_data=val_data,
    epochs=20
)

model.save("helmet_cnn.h5")

import cv2
import numpy as np
from ultralytics import YOLO
from tensorflow.keras.models import load_model

# Load trained models
yolo = YOLO("/content/runs/detect/train7/weights/best.pt")
cnn = load_model("helmet_cnn.h5")

IMG_SIZE = 128
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = yolo(frame)

    for r in results:
        for box in r.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            crop = frame[y1:y2, x1:x2]
            if crop.size == 0:
                continue

            img = cv2.resize(crop, (IMG_SIZE, IMG_SIZE))
            img = img / 255.0
            img = np.expand_dims(img, axis=0)

            pred = cnn.predict(img)[0][0]
            label = "Helmet" if pred > 0.5 else "No Helmet"
            color = (0,255,0) if label == "Helmet" else (0,0,255)

            cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
            cv2.putText(frame, label, (x1, y1-10),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, color, 2)

    cv2.imshow("Hybrid Helmet Detection", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

